create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  nom text not null,
  prenom text not null,
  message text not null,
  ip_hash text,
  created_at timestamptz not null default now()
);

create table if not exists public.banned_ips (
  ip_hash text primary key,
  created_at timestamptz not null default now()
);

alter table public.messages add column if not exists ip_hash text;
alter table public.banned_ips enable row level security;
alter table public.messages enable row level security;

drop policy if exists messages_select_public on public.messages;
drop policy if exists messages_insert_public on public.messages;
drop policy if exists messages_delete_public on public.messages;
drop policy if exists banned_ips_select_public on public.banned_ips;
drop policy if exists banned_ips_insert_public on public.banned_ips;

create policy messages_select_public
  on public.messages
  for select
  to anon
  using (true);

create policy messages_insert_public
  on public.messages
  for insert
  to anon
  with check (
    length(trim(nom)) > 0
    and length(trim(prenom)) > 0
    and length(trim(message)) > 0
    and length(trim(message)) <= 180
    and lower(message) not like '%pute%'
    and lower(message) not like '%salope%'
    and lower(message) not like '%connard%'
    and lower(message) not like '%connasse%'
    and lower(message) not like '%fdp%'
    and lower(message) not like '%encule%'
    and lower(message) not like '%enculé%'
    and lower(message) not like '%ntm%'
    and (
      ip_hash is null
      or not exists (
        select 1
        from public.banned_ips
        where banned_ips.ip_hash = messages.ip_hash
      )
    )
  );

create policy messages_delete_public
  on public.messages
  for delete
  to anon
  using (true);

create policy banned_ips_select_public
  on public.banned_ips
  for select
  to anon
  using (true);

create policy banned_ips_insert_public
  on public.banned_ips
  for insert
  to anon
  with check (length(trim(ip_hash)) > 0);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'messages'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;
end $$;
